version: '3'
services:
  nginx:
    container_name: estore-nginx
    build:
      context: ./.docker
      dockerfile: nginx.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    restart: unless-stopped
    volumes:
      - ./www:/var/webserver/www
      - ./log:/var/webserver/log
    depends_on:
      - php
      - redis
    networks:
      frontend:
      backend:
        aliases:
          - ${APP_NAME}

  php:
    container_name: estore-php
    build:
      context: ./.docker
      dockerfile: php.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    restart: unless-stopped
    ports:
      - ":9000"
    volumes:
      - ./www:/var/webserver/www
      - ./log:/var/webserver/log
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: estore-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - backend

  laravel-crontab:
    build:
      context: ./.docker
      dockerfile: php.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: estore-laravel-crontab
    volumes:
      - ./www:/var/webserver/www
      - ./log:/var/webserver/log
    working_dir: /var/webserver/www
    entrypoint: [ 'php', '/var/webserver/www/artisan', 'schedule:work' ]
    networks:
      - backend

  laravel-queue:
    build:
      context: ./.docker
      dockerfile: php.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: estore-laravel-queue
    volumes:
      - ./www:/var/webserver/www
      - ./log:/var/webserver/log
    working_dir: /var/webserver/www
    entrypoint: [ 'php', '/var/webserver/www/artisan', 'queue:work' ]
    networks:
      - backend

  composer:
    build:
      context: ./.docker
      dockerfile: composer.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: estore-composer
    volumes:
      - ./www:/var/webserver/www
      - ./log:/var/webserver/log
    working_dir: /var/webserver/www
    depends_on:
      - php
    user: ${USER:-laravel} #system user
    profiles: [ "composer" ]
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - backend

  artisan:
    build:
      context: ./.docker
      dockerfile: php.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: artisan
    volumes:
      - ./www:/var/webserver/www
      - ./log:/var/webserver/log
    working_dir: /var/webserver/www
    profiles: [ "artisan" ]
    entrypoint: [ 'php', '/var/webserver/www/artisan' ]
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
