version: '3'
services:
  # Open database ports for PhpStorm inspect
  db:
    ports:
      - "3306:3306"

  # Open nginx ports
  nginx:
    depends_on:
      - node
    ports:
      - "80:80"

  # NodeJs container to background frontend compilation
  node:
    image: node:19-alpine
    container_name: lws-node
    restart: "no"
    tty: true
    working_dir: /var/webserver/www
    command: "npm run host"
    volumes:
      - ./www:/var/webserver/www
    networks:
      - frontend
    ports:
      - "5173:5173"

  # NodeJs container to build frontend
  npm:
    profiles: ["npm"]
    image: node:alpine
    container_name: lws-npm
    volumes:
      - ./www:/var/webserver/www
    ports:
      - "3000:3000"
      - "3001:3001"
    working_dir: /var/webserver/www
    entrypoint: [ 'npm' ]
    networks:
      - backend

  # Email client to inspect mailing features
  mailhog:
    image: mailhog/mailhog:latest
    container_name: lws-mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend
