version: '3'
services:
  nginx:
    depends_on:
      - db

  php:
    depends_on:
      - db

  laravel-schedule:
    depends_on:
      - db

  laravel-queue:
    depends_on:
      - db

  artisan:
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    container_name: lws-database
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - ./.backups:/var/webserver/.backups
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - database:/var/lib/mysql
    networks:
      - backend

volumes:
  database:
